import Head from 'next/head'
import styles from '../styles/Home.module.css'
import PostList from '../components/PostList'

export default function Home({posts}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostList posts={posts}/>
        
      
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts?_limit=5")
  const posts = await res.json();
  return {
    props:{
      posts,
    },
  }
}
