import Head from 'next/head'
import Link from 'next/link'

export default function Videos({posts}) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Videos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        
      
    </div>
  )
}

export const getStaticProps = async () => {
  const res = await fetch("http://localhost:3000/api/videos")
  const posts = await res.json();

  return {
    props:{
      posts,
    },
  }
}